WIP

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,7 +1,14 @@
-# This file has been generated by `make_travis_yml_2.hs`
-# see https://github.com/hvr/multi-ghc-travis for more information
+# This Travis job script has been generated by a script via
+#
+#   make_travis_yml_2.hs 'hackage-server.cabal'
+#
+# For more information, see https://github.com/hvr/multi-ghc-travis
+#
 language: c
 sudo: false
+
+git:
+  submodules: false  # whether to recursively clone submodules
 
 cache:
   directories:
@@ -10,79 +17,69 @@ cache:
 
 before_cache:
   - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
-  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar
-
-notifications:
-  email:
-    # email is sent to the committer and the author, but only if they have access to this repository
-    # see https://docs.travis-ci.com/user/notifications/#Email-notifications for details
-    on_success: never
-    on_failure: always
-  irc:
-    channels:
-      - "chat.freenode.net#hackage"
-    template:
-      - "\x0313hackage-server\x0f/\x0306%{branch}\x0f \x0314%{commit}\x0f %{message} \x0302\x1f%{build_url}\x0f"
+  # remove files that are regenerated by 'cabal update'
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.*
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/*.json
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.cache
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar.idx
 
 matrix:
   include:
-    - env: CABALVER=1.24 GHCVER=7.6.3
-      compiler: ": #GHC 7.6.3"
-      addons: {apt: {packages: [cabal-install-1.24,ghc-7.6.3,alex-3.1.7,happy-1.19.5], sources: [hvr-ghc]}}
-    - env: CABALVER=1.24 GHCVER=7.8.4
-      compiler: ": #GHC 7.8.4"
-      addons: {apt: {packages: [cabal-install-1.24,ghc-7.8.4,alex-3.1.7,happy-1.19.5], sources: [hvr-ghc]}}
-    - env: CABALVER=1.24 GHCVER=7.10.3
-      compiler: ": #GHC 7.10.3"
-      addons: {apt: {packages: [cabal-install-1.24,ghc-7.10.3,alex-3.1.7,happy-1.19.5], sources: [hvr-ghc]}}
-    - env: CABALVER=1.24 GHCVER=8.0.1
-      compiler: ": #GHC 8.0.1"
-      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1,alex-3.1.7,happy-1.19.5], sources: [hvr-ghc]}}
+    - compiler: "ghc-7.6.3"
+    # env: CABALVER=head TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [cabal-install-head,ghc-7.6.3], sources: [hvr-ghc]}}
+    - compiler: "ghc-7.8.4"
+    # env: CABALVER=head TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [cabal-install-head,ghc-7.8.4], sources: [hvr-ghc]}}
+    - compiler: "ghc-7.10.3"
+    # env: CABALVER=head TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [cabal-install-head,ghc-7.10.3], sources: [hvr-ghc]}}
+    - compiler: "ghc-8.0.1"
+    # env: CABALVER=head TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [cabal-install-head,ghc-8.0.1], sources: [hvr-ghc]}}
 
 before_install:
+ - HC=${CC}
  - unset CC
- - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/happy/1.19.5/bin:/opt/alex/3.1.7/bin:$PATH
+ - CABALVER=${CABALVER-head}
+ - PATH=/opt/ghc/bin:/opt/cabal/$CABALVER/bin:$PATH
+ - PKGNAME='hackage-server'
 
 install:
  - cabal --version
  - BENCH=${BENCH---enable-benchmarks}
  - TEST=${TEST---enable-tests}
- - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
- - if [ -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz ];
-   then
-     zcat $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz >
-          $HOME/.cabal/packages/hackage.haskell.org/00-index.tar;
-   fi
+ - echo "$(${HC} --version) [$(${HC} --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - travis_retry cabal update -v
- - sed -i 's/^jobs:.*$/jobs:2/' ${HOME}/.cabal/config
- # install build-dependencies before script-phase
- - if [ -f configure.ac ]; then autoreconf -i; fi
- # temporarily disabled since --dep doesn't work yet, see https://github.com/haskell/cabal/issues/3490
- # - cabal new-build ${TEST} ${BENCH} --dep
- # - rm -rf dist-newstyle/
+ - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
+ - cabal new-build -w ${HC} ${TEST} ${BENCH} --dep -j2
 
 # Here starts the actual work to be performed for the package under test;
 # any command which exits with a non-zero exit code causes the build to fail.
 script:
- # test that a source-distribution can be generated
- - cabal sdist
+ - if [ -f configure.ac ]; then autoreconf -i; fi
+ - rm -rf dist/*.tar.*
+ - cabal sdist # test that a source-distribution can be generated
+ - cd dist/
+ - SRCTAR=(${PKGNAME}-*.tar.gz)
+ - SRC_BASENAME="${SRCTAR/%.tar.gz}"
+ - tar -xvf "./$SRC_BASENAME.tar.gz"
+ - cd "$SRC_BASENAME/"
+## from here on, CWD is inside the extracted source-tarball
+ - "echo 'packages: .' > cabal.project"
+ # this builds all libraries and executables (without tests/benchmarks)
+ - cabal new-build -w ${HC} --disable-tests --disable-benchmarks
+ # this builds all libraries and executables (including tests/benchmarks)
+ # - rm -rf ./dist-newstyle
+ - cabal new-build -w ${HC} ${TEST} ${BENCH}
 
- # extract the source-distribution and chdir into it
- - SRC_BASENAME=$(cabal info . | awk '{print $2;exit}')
- - tar -C dist/ -xf dist/$SRC_BASENAME.tar.gz
- - "echo 'packages: .' > dist/$SRC_BASENAME/cabal.project"
- - cd dist/$SRC_BASENAME/
-
- ## from here on, CWD is inside the extracted source-tarball
- ## Check that the resulting source distribution can be built w/o and w/ tests
- ## first pass, w/o tests
- - cabal new-build --disable-tests --disable-benchmarks
- ## and now with tests & benchmarks
- - cabal new-build ${TEST} ${BENCH}
-
- # there's no 'cabal new-test' yet, so call tests directly for now
- - T=PackageTests;  ./dist-newstyle/build/*/build/$T/$T --plain
- - T=HashTests;     ./dist-newstyle/build/*/build/$T/$T
- - T=HighLevelTest; ./dist-newstyle/build/*/build/$T/$T
+ # there's no 'cabal new-test' yet, so let's emulate for now
+ - TESTS=( $(awk 'tolower($0) ~ /^test-suite / { print $2 }' *.cabal) )
+ - if [ "$TEST" != "--enable-tests" ]; then TESTS=(); fi
+ - shopt -s globstar;
+   RC=true; for T in ${TESTS[@]}; do echo "== $T ==";
+   if dist-newstyle/build/**/$SRC_BASENAME/**/build/$T/$T; then echo "= $T OK =";
+   else echo "= $T FAILED ="; RC=false; fi; done; $RC
 
 # EOF
